server:
  port: 8079
spring:
  application:
    name: nfg_gunny_core
  data:
    mongodb:
      auto-index-creation: true
      uri: "mongodb+srv://thanhthien34c9:thien2991@nft.rogay.mongodb.net/?retryWrites=true&w=majority&appName=nft"
      database: nft_gunny_database
  messages:
    basename: ValidationMessages


logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
    security: TRACE