version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: nft_gunny_mongodb_container
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hoangsang236
      MONGO_INITDB_DATABASE: nft_gunny_database
    volumes:
      - mongo_data:/data/db
      - /Users/mailethanhthien/game gunny/nft_gunny_core/database/nft_gunny_database_backup:/data/backup

volumes:
  mongo_data:
    driver: local
